bluetooth: Add Battery Level ES7 Async sample
GoogleChrome/samples pull request #426
Opened 2016-10-10 12:55 UTC by beaufortfrancois

With ES7 Async functions (async await) in M55 now, I thought we may want to add a sample on how to use them with the Web Bluetooth API.

@jeffposnick @scheib @jyasskin @g-ortuno

See https://beaufortfrancois.github.io/samples/web-bluetooth/battery-level-async-await.html and https://beaufortfrancois.github.io/samples/web-bluetooth/index.html

![screenshot 2016-10-10 at 2 52 10 pm](https://cloud.githubusercontent.com/assets/634478/19236757/5d440d22-8ef9-11e6-9996-0126d25748bd.png)

2016-10-10 14:58 UTC, jeffposnick commented
The only feedback that I have is that ES7 isn't a meaningful term. It's colloquially used to describe anything that's due to be standardized but didn't make it into ES2015, but given its lack of precision, I'd leave it out.

I'd just refer to "async/await" without the "ES7" bit, and include a link to an article describing what it's all about. (@jakearchibald has one due to be published on Web Fundamentals, once the M55 beta ships.)

2016-10-10 19:02 UTC, scheib requested changes

2016-10-10 19:02 UTC, scheib commented on web-bluetooth/battery-level-async-await.js
> +  } catch(e) {
catch(error)

2016-10-11 11:05 UTC, beaufortfrancois commented on web-bluetooth/battery-level-async-await.js
> +  } catch(e) {
Oops. Thanks.

2016-10-11 11:10 UTC, beaufortfrancois commented
I've addressed all your feedback.
I'll add jake's article when it is up. Thanks!

2016-10-11 11:10 UTC, merged