CSS hyphens example
GoogleChrome/samples pull request #429
Opened 2016-10-17 21:17 UTC by jpmedley

2016-10-18 16:29 UTC, jeffposnick requested changes

2016-10-18 16:29 UTC, jeffposnick commented on css-hyphens/README.md
> +<!-- TODO: Replace PLACEHOLDER with feature name. -->
Can you remove this and the other comments from the file?

2016-10-18 16:29 UTC, jeffposnick commented on css-hyphens/index.html
> +  font: 18px Times;
I don't know how widely available `Times` is on different platforms. Maybe just go with `serif` here?

2016-10-19 20:01 UTC, jpmedley commented
@jeffposnick PTAL

2016-10-19 20:53 UTC, jeffposnick commented
👍

2016-10-19 20:54 UTC, merged