Tiny refactor of sample caching service worker
GoogleChrome/samples pull request #440
Opened 2016-11-14 14:59 UTC by mohawk2

Stumbled across this code from https://developer.mozilla.org/en-US/docs/Web/API/Cache

Comments/suggested changes welcome!

2016-11-14 15:17 UTC, mohawk2 commented
I signed it!

2016-11-14 16:25 UTC, ebidel requested changes

2016-11-14 16:25 UTC, ebidel commented on service-worker/selective-caching/service-worker.js
> +  return Object.keys(hash).map(function(key) { return hash[key]; });
no need for this function.  `Object.values(CURRENT_CACHES)` gives you the object's values.

2016-11-14 16:25 UTC, ebidel commented on service-worker/selective-caching/service-worker.js
> +  var expectedCacheNamesSet = array2set(hashValues(CURRENT_CACHES));
I think we should just create a proper `new Set()` and use it here. `array2set` is uneeded

2016-11-14 16:39 UTC, mohawk2 commented on service-worker/selective-caching/service-worker.js
> +  return Object.keys(hash).map(function(key) { return hash[key]; });
Learn something new every day, thanks! Done.

2016-11-14 16:45 UTC, mohawk2 commented on service-worker/selective-caching/service-worker.js
> +  var expectedCacheNamesSet = array2set(hashValues(CURRENT_CACHES));
Also quite right! Done.

2016-11-20 23:33 UTC, mohawk2 commented
I made the suggested changes. Was wondering what the process was for any next steps?

2017-01-30 13:33 UTC, beaufortfrancois commented
If @ebidel is OK, we'll merge it.

2017-05-02 13:28 UTC, mohawk2 commented
@ebidel Any objections?

2017-09-29 03:24 UTC, mohawk2 commented
...

2017-12-31 02:05 UTC, mohawk2 commented
@beaufortfrancois Been over a year now?

2018-01-02 08:08 UTC, beaufortfrancois commented
@ebidel WDYT?

2018-03-06 02:45 UTC, mohawk2 commented
...

2018-03-31 16:10 UTC, mohawk2 commented
Bueller?

2018-07-10 01:09 UTC, mohawk2 commented
Bueller?

2019-01-23 00:31 UTC, mohawk2 commented
Another year? Merge this, please.

2019-03-05 00:31 UTC, mohawk2 commented
@beaufortfrancois Been another year.

2019-03-06 04:02 UTC, ebidel commented
@jeffposnick should look at this.

2019-03-06 15:38 UTC, merged

2019-03-06 15:38 UTC, jeffposnick commented
Thanks for the heads-up.

2019-03-06 15:51 UTC, mohawk2 commented
Hallelujah!