Paymentrequest stickersheet
GoogleChrome/samples pull request #521
Opened 2017-06-29 13:47 UTC by mustafa-x

Created a stickersheet that designers and developer can use in Sketch

2017-06-29 14:06 UTC, beaufortfrancois commented
Hey @mustafa-x 
Here are few nits:
- Add `paymentrequest/stickersheet/index.html` to [`paymentrequest/index.html`](https://googlechrome.github.io/samples/paymentrequest/) as well. 
- `s/tak/take` in `paymentrequest/stickersheet/index.html`
- Replace `paymentrequest/stickersheet/index.html` header with
```
--- 
feature_name: PaymentRequest Stickersheet
chrome_version: 53 
feature_id: 5639348045217792 
--- 
```

2017-06-29 14:39 UTC, mustafa-x commented
hey @beaufortfrancois added changes just now :)

2017-06-29 14:45 UTC, beaufortfrancois commented
Thanks! Let me know when you're ready for review and want me to merge.

2017-06-29 14:50 UTC, mustafa-x commented
Feel free to review. I am waiting on another PR from Web Fundamentals as this links to that. Once that has been merged then we are good to go.

2017-06-30 09:02 UTC, beaufortfrancois requested changes
LGTM but nit.

2017-06-30 09:02 UTC, beaufortfrancois commented on paymentrequest/index.html
> +  <li><a href="https://googlechrome.github.io/samples/paymentrequest/stickersheet/index.html">Stickersheet</a>  -
You can simply use `/stickersheet/` there instead of the full URL.

2017-06-30 11:25 UTC, merged

2017-06-30 11:26 UTC, beaufortfrancois commented
Here it is live!
https://googlechrome.github.io/samples/paymentrequest/
https://googlechrome.github.io/samples/paymentrequest/stickersheet/