Remove deprecated payment network usage. Fix #53.
GoogleChrome/samples pull request #534
Opened 2017-08-16 13:47 UTC by dandv

2018-03-01 20:56 UTC, mnoorenberghe commented
The commit message should reference #533, not 53. Also, this problem affects some of the other payment demos too e.g. shipping-options.

@rsolomakhin Any chance of a merge so that conforming browsers can use the demos?

2018-03-01 21:00 UTC, rsolomakhin requested changes

2018-03-01 21:00 UTC, rsolomakhin commented on paymentrequest/credit-cards/demo.js
>      supportedMethods: ['basic-card'],
Could you also please change `['basic-card']` array to `'basic-card'` string? Thank you.

2018-05-24 19:32 UTC, HandOfGod1369 commented
https://www.w3.org/TR/html51/

2018-05-24 19:34 UTC, HandOfGod1369 commented
https://www.w3.org/TR/2016/CR-secure-contexts-20160915/

2018-07-17 15:25 UTC, PaulKinlan commented
@rsolomakhin I think this one can be closed now, the other PR fixed `supportedMethods`

2018-07-17 15:31 UTC, rsolomakhin commented
Agreed, @PaulKinlan

2018-07-17 15:32 UTC, rsolomakhin commented
@agektmr : Since you have the permissions here, please close this pull request. It is outdated.

2018-07-18 01:04 UTC, closed without merging