Added demo for intrinsic size
GoogleChrome/samples pull request #611
Opened 2018-09-12 19:04 UTC by loonybear

@ebidel PTAL thanks

2018-09-13 17:59 UTC, ebidel requested changes

2018-09-13 17:59 UTC, ebidel commented on intrinsic-size/sized.html
> +  var img = document.querySelector('#sizedImage');
use `const` for these

2018-09-13 17:59 UTC, ebidel commented on intrinsic-size/sized.html
> +  var output = "width = " + img.width + ", height = " + img.height +
use an template string instead of the concatenation

2018-09-13 17:59 UTC, ebidel commented on intrinsic-size/sized.html
> +  var img = document.querySelector('#sizedImage');
same with the other demos

2018-09-13 17:59 UTC, ebidel commented on intrinsic-size/sized.html
> +  var output = "width = " + img.width + ", height = " + img.height +
same with the other demos

2018-09-13 17:59 UTC, ebidel commented on intrinsic-size/index.html
> +<style>
can we move the styles to the top?

2018-09-13 17:59 UTC, ebidel commented on intrinsic-size/index.html
> +  button.classList.toggle("active");
use single quotes where possible.

2018-09-13 17:59 UTC, ebidel commented on intrinsic-size/index.html
> +  var demo = button.nextElementSibling;
`const`

2018-09-13 18:16 UTC, loonybear commented
Done. PTAL.

2018-09-13 20:54 UTC, ebidel requested changes

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +This attribute overrides the actual intrinsic size of an media element. Specifically, the image would raster at these
of an media -> of a media

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +    background-color: #777;
2-space indent on the blocks.

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +<button class="demoButton" onclick="toggleDemo(this)">See Demo</button>
I was a bit confused on why the demos are hidden by default and remove the toggle? Can we just show them all? There's only 3 :)

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +<center class="demoContent">
Oof. Let's not use `<center>`. That's old school! Use CSS `text-align-center` to center things.

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +  <div align="left">
likewise `align="left"` is pretty. Use CSS `text-align:left` if you need to adjust.

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +
Need this before your html content:

`{% include output_helper.html %}`

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +<p>if no width/height are otherwise set on an image, then the size is specified by &quot;intrinsicsize&quot;.</p>
if -> If

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +combination with <a hred="https://github.com/WICG/feature-policy/blob/master/policies/unsized-media.md">&quot;unsized-media&quot; policy</a>
hred -> href

2018-09-13 20:54 UTC, ebidel commented on intrinsic-size/index.html
> +combination with <a hred="https://github.com/WICG/feature-policy/blob/master/policies/unsized-media.md">&quot;unsized-media&quot; policy</a>
policy -> feature policy

2018-09-13 20:55 UTC, ebidel commented
One question I have about the feature is how it plays with https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit. `object-fit` is intended to maintain aspect ratio.

Maybe you could add 1-2 sentence in the demo description that address that for readers?

2018-09-14 16:41 UTC, loonybear reviewed
Done. Please take another look. Thanks!

2018-09-14 16:52 UTC, ebidel approved these changes

2018-09-14 17:30 UTC, loonybear commented
Updated description. Ready to merge.

2018-09-14 20:52 UTC, merged